name: social_foundation_example
description: Demonstrates how to use the social_foundation plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: ^3.1.0
  event_bus: ^1.1.1
  sqflite: ^1.2.0
  path_provider: ^1.6.0
  date_format: ^1.0.8
  image_picker: ^0.6.3+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  social_foundation:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/