name: deploy to pub dev
on:
  push:
    tags: 
      - 'v*.*.*'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: publish
        uses: sakebook/actions-flutter-pub-publisher@v1.2.1
        with:
          credential: ${{ secrets.PUB_CREDENTIAL }}
